production_url: "http://www.sigil.org"
date_format: '%d %B %Y'

"theme-sigil":
    use: "theme"

_root:
    rss:
        enable: false
    paginator:
        enable: false

posts:
    sort: ["date", "desc"]
    permalink : '/:year/:month/:title'
    latest: 1
    rss:
        enable: true
        limit: 10
    paginator:
        enable: false
        url: "/blog/index/"
        per_page: 1

asset_pipeline:
    enable: true
